"""This file plots the results generated by test2.cpp."""
import sys
sys.path.insert(0, "../")
import os
import igraph
import matplotlib.pyplot as pyplot

def main():
  extension = '.test2'
  dir_name = './results/'
  rep = 30
  for filename in os.listdir(dir_name):
    if not filename.endswith(extension):
      continue
    print 'Processing ' + filename
    pathname = dir_name + filename
    f = open(pathname, 'r')
    alpha = f.readline()
    print alpha
    degrees = [int(_x) for _x in f.readline().split(',')]
    cnt = [int(_x) for _x in f.readline().split(',')]
    m = {} # m<deg, sum of the reliability>
    freq = {} # freq<deg, qty of nodes with degree deg>
    for i in xrange(len(degrees)):
      if degrees[i] in m:
        m[degrees[i]] += cnt[i] * 1.0 / (rep * len(degrees))
        freq[degrees[i]] += 1
      else:
        m[degrees[i]] = cnt[i] * 1.0 / (rep * len(degrees))
        freq[degrees[i]] = 1
    x = []
    y = []
    for deg in m:
      if deg > 40:
        continue
      x.append(deg)
      y.append(m[deg] * 1.0 / freq[deg])
      if y[-1] > 1:
        print y[-1]
    pyplot.plot(x, y, 'o-', label=alpha)
  pyplot.legend()
  pyplot.yscale('log')
  pyplot.show()

if __name__ == '__main__':
  main()